$(document).ready(function(){
    $('#id1').owlCarousel({
        loop:true,
        margin:34,
        nav:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:3
            }
        }
    });
    $('#id2').owlCarousel({
        loop:false,
        margin:0,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:4
            }
        }
    });
    $('#id3').owlCarousel({
        loop:false,
        margin:100,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1366:{
                items:2,
                margin:90,
            },
            1920:{
                items:2
            }
        }
    });
});